schema:
    ./src/ts/schema/index.ts:
        require: ts-node/register
# documents: './client/src/graphql/**/*.ts'
extensions:
    generate:
        db:
            dbConfig:
                user: postgresql
                password: postgres
                database: users
                host: localhost
                port: 55432
            database: pg
        graphqlCRUD:
            create: true
            update: true
            findAll: true
            find: true
            delete: false
            subCreate: false
            subUpdate: false
            subDelete: false
            disableGen: false
        folders:
            model: ./model
            resolvers: ./src/ts/resolvers
            schema: ./src/ts/schema
            # client: ./src/ts/graphql
    codegen:
        ./src/ts/generated-types/server.ts:
            plugins:
                - typescript
                - typescript-resolvers
        ./src/ts/generated-types/client.tsx:
            plugins:
                - typescript
                - typescript-operations
                - typescript-react-apollo
            config:
                withComponent: false
                withHOC: false
                withHooks: true
